# Generated by Django 3.2 on 2021-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobileNumber', models.IntegerField(blank=True)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('emailId', models.CharField(max_length=64)),
                ('loginStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobileNumber', models.IntegerField(blank=True)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('emailId', models.CharField(blank=True, max_length=64)),
                ('enrollmentNuumber', models.IntegerField()),
                ('loginStatus', models.BooleanField()),
            ],
        ),
    ]
