# Generated by Django 3.2 on 2021-11-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='loginStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='loginStatus',
            field=models.BooleanField(default=False),
        ),
    ]
