# Generated by Django 3.2 on 2021-11-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211103_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollmentNuumber',
            new_name='enrollmentNumber',
        ),
    ]
