# Generated by Django 3.2 on 2021-11-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_enrollmentnuumber_student_enrollmentnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobileNumber', models.IntegerField(blank=True)),
                ('emailId', models.CharField(blank=True, max_length=64)),
                ('enrollmentNumber', models.IntegerField()),
                ('loginStatus', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
            ],
        ),
    ]
