# Generated by Django 3.2 on 2021-11-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_newstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstudent',
            name='loginStatus',
        ),
    ]
