# Generated by Django 3.2 on 2021-11-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_newstudent_loginstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('Education', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Written_Books', to='mainapp.author')),
            ],
        ),
        migrations.AlterField(
            model_name='librarian',
            name='emailId',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='mobileNumber',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='emailId',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollmentNumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='BookDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookIsbnNumber', models.IntegerField()),
                ('BookAvalibilityStatus', models.BooleanField(default=True)),
                ('BookReserverdStatus', models.BooleanField(default=False)),
                ('BookDuedate', models.DateTimeField(blank=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Copies_of_book', to='mainapp.book')),
                ('Student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Taken_Books', to='mainapp.student')),
            ],
        ),
    ]
