# Generated by Django 3.2 on 2021-11-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211105_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='Authors',
            field=models.ManyToManyField(blank=True, related_name='Written_Books', to='mainapp.Author'),
        ),
    ]
