# Generated by Django 3.2 on 2021-11-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211105_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatabase',
            name='BookDuedate',
            field=models.DateTimeField(null=True),
        ),
    ]
