# Generated by Django 3.2 on 2021-11-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_bookdatabase_bookduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatabase',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Taken_Books', to='mainapp.student'),
        ),
    ]
