# Generated by Django 3.2 on 2021-11-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_bookdatabase_bookissuedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdatabase',
            name='Reserved_Stu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reserverd_Books', to='mainapp.student'),
        ),
    ]
