# Generated by Django 3.2 on 2021-11-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_bookdatabase_reserved_stu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatabase',
            name='Reserved_Stu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reserverd_Books', to='mainapp.student'),
        ),
        migrations.AlterField(
            model_name='bookdatabase',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Taken_Books', to='mainapp.student'),
        ),
    ]
