# Generated by Django 3.2 on 2021-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211105_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatabase',
            name='BookIsbnNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
