# Generated by Django 3.2 on 2021-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_bookdatabase_bookisbnnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(blank=True),
        ),
    ]
